# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/COA experiments/exam 2/CPU_V2.1/CPU_V2.1.srcs/sources_1/ip/control_memory/control_memory.xci
# IP: The module: 'control_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/COA experiments/exam 2/CPU_V2.1/CPU_V2.1.srcs/sources_1/ip/control_memory/control_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'control_memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/COA experiments/exam 2/CPU_V2.1/CPU_V2.1.srcs/sources_1/ip/control_memory/control_memory.xci
# IP: The module: 'control_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/COA experiments/exam 2/CPU_V2.1/CPU_V2.1.srcs/sources_1/ip/control_memory/control_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'control_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
